### ISSUE TITLE
NullPointerException in AFKListener on reload

### ISSUE THREAD

**Issue by ifvictr** [hackclub/HCCore#77] opened 2020-04-19 05:28 UTC
PlayerMoveEvent and PlayerInteractEvent have been observed throwing NPE errors on reload so far.

**Comment by nice6599** [comment] 2020-04-23 19:25
Can you add steps to reproduce this error?

**Comment by ifvictr** [comment] 2020-04-23 21:19
I haven't really dug into it, but it seems like the errors are thrown when players move/interact and their PlayerData sessions haven't been initialized yet.

**Comment by nice6599** [comment] 2020-04-26 18:43
okay i did some basic testing and it seems like the error is caused by `.setLastActiveAt()`
if you remove that there are no problems. if you remove `System.currentTimeMillis()` and replace it with an integer you still run into problems.

**Comment by nice6599** [comment] 2020-04-26 19:05
## Initial analysis
Weirdly when you type into chat while the server is reloading you trigger two errors one in `AFKListener.java` and another in `PlayerListener.java`

in `AFKListener.java` it seems that the error is triggered by `.setLastActiveAt()` whereas in `PlayerListener.java` it seems to be triggered by the `data.getMessageColor()` both of these methods are found in `PlayerData.java` which says to me that that file is where the problem stems from. 

### You can trigger this same error by doing any of the following during reload
* sending message to chat
* placing blocks 
* moving
* executing any command that is added by the HCCore plugin
#### this is what is untested but i believe will still throw errors 
* dying
* taking damage
* re spawning
* joining the game
* leaving the game

**Comment by ifvictr** [comment] 2020-04-26 23:04
It's also worth noting that Spigot recommends doing a full restart instead of `/reload`.

**Comment by nice6599** [comment] 2020-04-30 18:47
is there any way to fix this? or are we just gonna have to deal with it?

**Comment by eankeen** [comment] 2020-11-06 09:21
I replicated this too - seems like there is no way to fix it - most of the time hot reloading code has idiosyncrasies and can cause buggy behavior, especially if the implementation isn't officially supported by the whole toolchain (and it's [no different](https://matthewmiller.dev/blog/problem-with-reload) in the case of Spigot/Paper. i'm closing this now because it only is activated when using Bile under the specific circumstances @nice6599 mentioned and if we could theoretically fix it here, it would only make the codebase more cryptic

**Closed by eankeen** 2020-11-06 09:21 UTC
Labels: bug, help wanted

**Comment by zanedb** [comment] 2020-11-06 17:29
I think the solution is to use reload as infrequently as possible, it's really not great for a bunch of reasons (this being one). Plugins like ServerUtils that can reload individual plugins are preferred.
